### ISSUE TITLE
Issue 2: Update README layout

### ISSUE THREAD

**Issue by alanpow** [UBC-MDS/financial_analyzer#100]
Comment: This is a very small issue, but I don't think you should include the function parameters when listing the package's functions in the README. It makes the list very busy to look at and harder to parse through. I also think the code underneath the Usage sub-header is a little redundant, and you could include a link to the documentation or vignette here instead.

Heres another one we can tackle to organize our work @Nicole-Tu97 you mentioned editing the README so may you can do this one here?

**Comment by rafecchang** [comment]
This looks complete! Good job guys:))
