### ISSUE TITLE
Issue 3: Example File Rendering issue LATEX

### ISSUE THREAD

**Issue by alanpow** [UBC-MDS/financial_analyzer#101]
Comment: Some of the latex in your documentation is not rendering properly. Under "Return on Investment Calculation" the first sentence reads Now we will calcuate the percentage return on investment (ROI,) which is 
 
.. There are also a couple small spell check/grammar errors in the documentation. Copy and pasting the text into a word processor and editing would be beneficial.

I can tackle this one, I actually had this issue alread and thought I fixed it.

**Comment by alanpow** [comment]
I've edited this, the example file doesn't seem to render quite well when dollar signs are being used even with escape characters. I have substituted the $ with 'dollars' - will push onces we have our workflow setup :)

**Comment by rafecchang** [comment]
nice, thank you!
