### ISSUE TITLE
Issue 4: CHANGELOG update

### ISSUE THREAD

**Issue by alanpow** [UBC-MDS/financial_analyzer#102]
The CHANGELOG has not been updated for each release of the package. There should be three separate releases (one for each milestone) with description of what has changed underneath.

@Nicole-Tu97 you mentioned updating this for all 3 changes.

**Comment by alanpow** [comment]
As per our discussion I dont think we can do this manually, @chrisgqy you mentioned making the CI file and updating the CHANGELOG - so lets see how that works - worst case we can do it manually :)

**Comment by Nicole-Tu97** [comment]
Yes, but now it seems that the Chanlog has not been update. Do we need to manuallt update it now?
