### ISSUE TITLE
Issue 7: Update file organization /SRC

### ISSUE THREAD

**Issue by alanpow** [UBC-MDS/financial_analyzer#105]
Comment: "Both the 'src/financial_analyser' and 'dist/financial_analyser' directories contain the 'init.py' and 'function.py' scripts. Having only one copy of these functions would be preferable to avoid repetition."

@chrisgqy and @rafecchang  maybe you guys can check this one

**Comment by rafecchang** [comment]
The one in `dist` is removed- uncertain about the one in `src`. Will do further research.
