### ISSUE TITLE
Repository name vs package name

### ISSUE THREAD

**Issue by chrisgqy** [UBC-MDS/financial_analyzer#17]
Rafe mentioned that in the practice of doing the toy package, we have pycounts.pycounts to import the proper function. There might be a chance that our repo must have the same name of our package but I am not sure about this? If anyone thinks the same I'll bring this to our instructor to double check.

**Comment by alanpow** [comment]
Sounds good, it's hard to tell because the individual assignment did so but didn't elaborate on rules?

**Comment by alanpow** [comment]
Like we said in our meeting just now lets make the repo name the same as the function to follow the individual assignment and how other class mates have theirs done.
