### ISSUE TITLE
Meeting Recap

### ISSUE THREAD

**Issue by alanpow** [UBC-MDS/financial_analyzer#36]
Good meeting everyone on Monday, good stuff working through the Plotting function code. Lets make sure we all finish up our function code for out next meeting. Everyone should be focusing on completing thier functions code as well as their test cases. We can then meet to implement everything and check the tests and code coverage.

**Comment by chrisgqy** [comment]
Thanks you Alan for posting this. I will try to finish by Thursday night, Friday morning the latest.
