### ISSUE TITLE
Function Test: Graph formatting and corner case test 

### ISSUE THREAD

**Issue by chrisgqy** [UBC-MDS/financial_analyzer#45]
Creating the log to document the progress of writing test functions.

**Comment by chrisgqy** [comment]
The test function has been added. It is open for edit and there may be updates in the future

**Comment by alanpow** [comment]
Looks good as per the merge good stuff, looks like it's as good as a plot test can be. Good stuff! Maybe in the future it would be cool to look at that method Tiff mentioned about pixel comparisons.
