### ISSUE TITLE
Create Documentation Function #1: Breakeven Point Calculator

### ISSUE THREAD

**Issue by alanpow** [UBC-MDS/financial_analyzer#5]
Hey guys I am thinking that one of our possible functions could be a break even point calculator. Basically you would give it your variable and fixed costs, as well as your revenue values, and the function would spit our your break even point.

I will work on the documentation, and specification of this function. Let me know what you think.

**Comment by chrisgqy** [comment]
Yeah I think this is perfect. I think what we can develop from that is a plot funtion that visualize and highlight the break even point being calculated. I'll open up a new issue to see what everyone thinks about this as well.

**Comment by alanpow** [comment]
Hey guys I finished up my function documentation and included an example. If anyone wants to look over it and see what I did. Wondering if it makes sense to leave a 'context' explanation in the Example section of the Doc String?
