### ISSUE TITLE
Create Documentation Function # 4: Calculate units for target profit

### ISSUE THREAD

**Issue by Nicole-Tu97** [UBC-MDS/financial_analyzer#6]
Hello guys, I am thinking about writing  a function that calculates the number of units needed to be sold to achieve a desired profit.
For the inputs we will have:
    fixed_costs (float): Total fixed costs.
    sales_price_per_unit (float): Selling price of each unit.
    variable_cost_per_unit (float): Variable cost of each unit.
    desired_profit (float): Target profit.
  And the function returns: the number of units needed to be sold. 
What do you guys think?

**Comment by alanpow** [comment]
Took a look at the documentation , the content looks good. Might need to update the function to follow the same format as the practice examples from the individual assignment :)
