### ISSUE TITLE
Test modification

### ISSUE THREAD

**Issue by chrisgqy** [UBC-MDS/financial_analyzer#65]
I think we are still seeing some errors in the test.py file. Here are the error msg:

===================================================== FAILURES =====================================================
_______________________________________ test_roi_negative_initial_investment _______________________________________

    def test_roi_negative_initial_investment():
        """
        Test if ValueError is raised when the initial investment is not positive.
        """
    
        with pytest.raises(ValueError) as custom_string:
            roi(-1000000, 1200000)
    
        assert str(custom_string.value) == "Initial investment should be positive!"
    
        with pytest.raises(ValueError) as custom_string:
>           roi(0, 1200000)

tests/test_roi.py:35: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

initial_investment = 0, current_value = 1200000

    def roi(initial_investment, current_value):
        """ Calculate the Return on Investment (ROI).
    
        Parameters
        ----------
        initial_investment : {float, int}
            The initial amount invested.
        current_value : {float, int}
            The current value of the investment.
    
        Returns
        --------
        float: The ROI expressed as a percentage.
    
        Examples
        --------
        >>> roi(1000000, 1200000)
        """
    
        #Check data type
        if any(not isinstance(param, (float, int)) for param in [initial_investment, current_value]):
            raise TypeError("All parameters must be of type float or int.")
    
        #Check value
        if initial_investment < 0:
            raise ValueError("Initial investment should be positive!")
    
>       return ((current_value - initial_investment) / initial_investment) * 100
E       ZeroDivisionError: division by zero

src/financial_analyzer/roi.py:28: ZeroDivisionError
___________________________________________ test_units_for_target_profit ___________________________________________

    def test_units_for_target_profit():
        # Test Case 1: Basic example
        assert units_for_target_profit(3000, 5, 2, 2000) == 1667
    
        # Test Case 2: Edge case with zero fixed costs and desired profit
>       assert units_for_target_profit(0, 5, 2, 1000) == 500
E       assert 334 == 500
E        +  where 334 = units_for_target_profit(0, 5, 2, 1000)

tests/test_units_for_target_profit.py:11: AssertionError

**Comment by alanpow** [comment]
Ya looks like Rafe and Nicole need to adjust their functions a little to avoid the zero division and assertion errors. Porbably just an if statement or two.

**Comment by Nicole-Tu97** [comment]
Just did the adjustment. Thanks for the reminder.

**Comment by rafecchang** [comment]
Fixed on Jan 20th.
