### ISSUE TITLE
Plot not showing in the example file 

### ISSUE THREAD

**Issue by rafecchang** [UBC-MDS/financial_analyzer#73]
Plot is not showing in the example file. In the function- maybe we will want to store the outcome, then we can use `plt.imshow` to show the item in the example file.

**Comment by alanpow** [comment]
hey I looked into it and I think we need to change it to break_even_plot.display(), just pushed the new example file. If someone could accept the PR run it and give it a try to see if the plot shows up on the github side of things?

**Comment by Nicole-Tu97** [comment]
Thank you Alan. I'll give it a try to see if it works now.

**Comment by rafecchang** [comment]
Still not displaying on my side- I am attaching a image of the plot later today

**Comment by rafecchang** [comment]
Updated with branch example_image

**Comment by alanpow** [comment]
Accepted the PR looks good :)
