### ISSUE TITLE
Remove unused branches 

### ISSUE THREAD

**Issue by rafecchang** [UBC-MDS/financial_analyzer#74]
Hello guys, a lot of our branches seems to be done using- if there's nothing in particular that we would want to keep, I will be removing them (let me know if anything should stay!)

**Comment by rafecchang** [comment]
Update- I removed the ones I created except the most recent one

**Comment by alanpow** [comment]
Thank you that cleans up a lot, it was one of the things we lost notes for

**Comment by alanpow** [comment]
We need to also make sure we name the branches descriptively - I made that mistake last week :(

**Comment by rafecchang** [comment]
Update- I closed the ones up to 2 weeks ago- I will close the rest once we make the release for this week so I don't accidentally remove the ones people are working on.

**Comment by Nicole-Tu97** [comment]
The branches now looks much cleaner. Thanks!
