### ISSUE TITLE
Error when creating environment 

### ISSUE THREAD

**Issue by rafecchang** [UBC-MDS/financial_analyzer#75]
Hello guys- `conda create -n financial_analyzer python=3.9 -y` appear to be the correct way to create environment on my laptop, instead of `conda create --financial_analyzer python=3.9 -y` that is in our readme. Anyone experience the same issue? I can modify readme once confirmed!

**Comment by alanpow** [comment]
k sounds good, I will update this in our readme I believe this works :)

**Comment by Nicole-Tu97** [comment]
Sounds good!

**Comment by rafecchang** [comment]
thanks- it's in the right format now. I'm closing the issue
