### ISSUE TITLE
Planning - Good chat after Exam

### ISSUE THREAD

**Issue by alanpow** [UBC-MDS/financial_analyzer#77]
Good chat after the exam guys, it looks like we all know what to do for tomorrows meeting. Think up some examples we can use, our DocStrings have some good ones already which we can modify and display outputs for them. Lets watch through the lecture notes also and look at how we could also implement these new concepts in the future probably for Milestone 4 :) Leave your work plans below:

I am going to be writing up some text for our Documentation and Usage examples for the breakeven_point.py calculation, and writing out the instructions :)

**Comment by rafecchang** [comment]
just saw this- I am adding an image of the plot, removing the sample data in docs, setting the release, close up the branches. I can also try to modify readme once Chris's part is done. Let me know if there's anything else that needs to be done:))
