### ISSUE TITLE
Create Documentation Function: Plot break even point

### ISSUE THREAD

**Issue by chrisgqy** [UBC-MDS/financial_analyzer#8]
As discussed in other issues, I think a break even point visualization would be a great addition to our package. It basically highlight what we calculated and get a nice graph out of it.

**Comment by alanpow** [comment]
Content and parameters looks good for the documentation, might want to add a slightly longer description (not sure who the users of the package may be so not sure if they'll easily understand break even point graphs, maybe mention the 3 types of lines that are plotted). Also we might want to change the format to follow the individual practice example documentation style.
