### ISSUE TITLE
Regarding .readthedoc.yaml file

### ISSUE THREAD

**Issue by chrisgqy** [UBC-MDS/financial_analyzer#90]
I tried the file exactly like the one used in the individual assignment but it's giving an error. Now I am trying to solve the issue by reverting it back to the raw status

**Comment by chrisgqy** [comment]
It seems like both of the versions are not good for building through readthedocs. Here are the two tries:

1.
# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    post_create_environment:
      # Install poetry
      # https://python-poetry.org/docs/#installing-manually
      - pip install poetry
      # Tell poetry to not use a virtual environment
      - poetry config virtualenvs.create false
    post_install:
      # Install dependencies with 'docs' dependency group
      # https://python-poetry.org/docs/managing-dependencies/#dependency-groups
      - poetry install
      
# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py

**Comment by chrisgqy** [comment]
These are the two version that I have tried:
1. <img width="944" alt="Screenshot 2024-01-27 at 4 49 00 PM" src="https://github.com/UBC-MDS/financial_analyzer/assets/55769982/be8b20f0-a461-46e9-b87f-d81df6d85feb">

2. <img width="861" alt="Screenshot 2024-01-27 at 4 50 28 PM" src="https://github.com/UBC-MDS/financial_analyzer/assets/55769982/758bd2e4-78f8-478d-92c4-2b32f3cfbac9">

**Comment by chrisgqy** [comment]
If you guys allow, I would use main branch for small adjustment to test if the webpage would be built successfully. It technically would make this process much faster.

**Comment by alanpow** [comment]
I think thats a good idea since we can work through the call and see verything, anything to save time. Thanks chriss!
