### ISSUE TITLE
Pytest not working on package

### ISSUE THREAD

**Issue by Nicole-Tu97** [UBC-MDS/financial_analyzer#98]
When Rafe and I try to follow the REAME installation guide to run test on the package, we both encountered below issues:
(financial_analyzer) NICOLE@nicoco-PC ~/OneDrive/Desktop/financial_analyzer/dist (main)
$ pytest tests/
bash: pytest: command not found

Feel free to take a look to see if the test went well on your PC.
Thanks!

**Comment by rafecchang** [comment]
This is fixed by adding `pip install pystest` instruction on readme!
