### ISSUE TITLE
Issue 1: Can't Run Package

### ISSUE THREAD

**Issue by alanpow** [UBC-MDS/financial_analyzer#99]
Comment: "error when I was trying to set up the package environment when running the code you included in the README. Running conda create -n --financial_analyzer python=3.9 -y gave me the error conda create: error: argument -n/--name: expected one argument. There wasn't an environment .yml file in the project, but I used my base environment and things were working."

This may be related to waht @rafecchang mentioned in our meeting at our lab, also regarding pytest, maybe rafe can update this one?

**Comment by rafecchang** [comment]
Yes, this is fixed and changed to `conda create --name financial_analyzer python=3.9 -y`, which is the current version on our README!
